/*
 * File: app/store/BookPrintQuality.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.BookPrintQuality', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'BookPrintQuality',
            data: [
                {
                    book_print_quality: 'black_and_white_but_poor_quality',
                    quality_label: 'Poor Quality Prints in Black & White'
                },
                {
                    book_print_quality: 'black_and_white_but_fine_quality',
                    quality_label: 'High Quality Prints in Black & White'
                },
                {
                    book_print_quality: 'coloured_but_poor_quality',
                    quality_label: 'Poor Quality Prints with some Texts or Images in Colours'
                },
                {
                    book_print_quality: 'coloured_but_fine_quality',
                    quality_label: 'High Quality Prints with some Texts or Images in Colours'
                }
            ],
            fields: [
                {
                    name: 'book_print_quality'
                },
                {
                    name: 'quality_label'
                }
            ]
        }, cfg)]);
    }
});