/*
 * File: app/store/BookPrimaryAudience.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.BookPrimaryAudience', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'BookPrimaryAudience',
            data: [
                {
                    book_target_demography: 'students',
                    target_label: 'Students'
                },
                {
                    book_target_demography: 'teachers',
                    target_label: 'Teachers'
                },
                {
                    book_target_demography: 'professionals',
                    target_label: 'Professionals'
                },
                {
                    book_target_demography: 'researchers',
                    target_label: 'Researchers'
                },
                {
                    book_target_demography: 'All',
                    target_label: 'Idle For Everybody'
                },
                
            ],
            fields: [
                {
                    name: 'book_target_demography'
                },
                {
                    name: 'target_label'
                }
            ]
        }, cfg)]);
    }
});