/*
 * File: app/store/BusinessCategory.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.BusinessCategory', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'BusinessCategory',
            data: [
                {
                    business_category: 'Telecommunication'
                },
                {
                    business_category: 'Banking & Finance'
                },
                {
                    business_category: 'Humanities'
                },
                {
                    business_category: 'Insurance'
                },
                {
                    business_category: 'Agriculture'
                },
                {
                    business_category: 'Government'
                },
                {
                    business_category: 'Education'
                },
                {
                    business_category: 'Health'
                },
                {
                    business_category: 'Oil & Gas'
                },
                {
                    business_category: 'Manufacturing'
                },
                {
                    business_category: 'Information & Communication Technology'
                },
                {
                    business_category: 'Software'
                },
                {
                    business_category: 'Services'
                },
                {
                    business_category: 'Retail'
                },
                {
                    business_category: 'Pharmaceutical'
                },
                {
                    business_category: 'Sports'
                },
                {
                    business_category: 'Media'
                },
                {
                    business_category: 'Entertainment'
                },
                {
                    business_category: 'Consultancy'
                },
                {
                    business_category: 'Others'
                }
            ],
            fields: [
                {
                    name: 'business_category'
                }
            ]
        }, cfg)]);
    }
});