/*
 * File: app/store/ClothesMeasurementUnits.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.ClothesMeasurementUnits', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ClothesMeasurementUnits',
            data: [
                {
                    clothes_measurement_unit: 'centimeter',
                    measurement_label: 'Centimeter'
                },
                {
                    clothes_measurement_unit: 'meter',
                    measurement_label: 'Meter'
                },
                {
                    clothes_measurement_unit: 'inches',
                    measurement_label: 'Inches'
                },
                {
                    clothes_measurement_unit: 'yards',
                    measurement_label: 'Yards'
                },
                
            ],
            fields: [
                {
                    name: 'clothes_measurement_unit'
                },
                {
                    name: 'measurement_label'
                }
            ]
        }, cfg)]);
    }
});