/*
 * File: app/store/ClothesDimensionLabels.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.ClothesDimensionLabels', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ClothesDimensionLabels',
            data: [
                {
                    clothes_dimension_label: 'small',
                    label_type: 'Small'
                },
                {
                    clothes_dimension_label: 'medium',
                    label_type: 'Medium'
                },
                {
                    clothes_dimension_label: 'large',
                    label_type: 'Large'
                },
                {
                    clothes_dimension_label: 'extra_large',
                    label_type: 'Extra Large'
                },
                {
                    clothes_dimension_label: 'extra_extra_large',
                    label_type: 'Extra Extra Large'
                },
                {
                    clothes_dimension_label: 'biggy',
                    label_type: 'Biggy'
                }
            ],
            fields: [
                {
                    name: 'clothes_dimension_label'
                },
                {
                    name: 'label_type'
                }
            ]
        }, cfg)]);
    }
});