/*
 * File: app/store/ClothesHandLengthTypes.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.ClothesHandLengthTypes', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ClothesHandLengthTypes',
            data: [
                {
                    clothes_hand_length_type: 'short_sleeve',
                    type_label: 'Short Sleeve'
                },
                {
                    clothes_hand_length_type: 'long_sleeve',
                    type_label: 'Long Sleeve'
                },
                {
                    clothes_hand_length_type: 'sleeveless',
                    type_label: 'Sleeveless'
                },
                
            ],
            fields: [
                {
                    name: 'clothes_hand_length_type'
                },
                {
                    name: 'type_label'
                }
            ]
        }, cfg)]);
    }
});