/*
 * File: app/store/ClothesTypes.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.ClothesTypes', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ClothesTypes',
            data: [
                {
                    clothes_type: 'baby_grow',
                    type_label: 'Babies'
                },
                {
                    clothes_type: 'ball_gown',
                    type_label: 'Ball Gown'
                },
                {
                    clothes_type: 'belt',
                    type_label: 'Belt'
                },
                {
                    clothes_type: 'bikini',
                    type_label: 'Bikini'
                },
                {
                    clothes_type: 'blazer',
                    type_label: 'Blazer'
                },
                {
                    clothes_type: 'blouse',
                    type_label: 'Blouse'
                },
                {
                    clothes_type: 'bow_tie',
                    type_label: 'Bow Tie'
                },
                {
                    clothes_type: 'boxers',
                    type_label: 'Boxers'
                },
                {
                    clothes_type: 'bra',
                    type_label: 'Bra'
                },
                {
                    clothes_type: 'bra_and_knicker_set',
                    type_label: 'Bra And Knicker Set'
                },
                {
                    clothes_type: 'briefs',
                    type_label: 'Briefs'
                },
                {
                    clothes_type: 'camisole',
                    type_label: 'Camisole'
                },
                {
                    clothes_type: 'cardigan',
                    type_label: 'Cardigan'
                },
                {
                    clothes_type: 'cargos',
                    type_label: 'Cargos'
                },
                {
                    clothes_type: 'catsuit',
                    type_label: 'Catsuit'
                },
                {
                    clothes_type: 'chemise',
                    type_label: 'Chemise'
                },
                {
                    clothes_type: 'coat',
                    type_label: 'Coat'
                },
                {
                    clothes_type: 'corset',
                    type_label: 'Corset'
                },
                {
                    clothes_type: 'cravat',
                    type_label: 'Cravat'
                },
                {
                    clothes_type: 'cufflinks',
                    type_label: 'Cufflinks'
                },
                {
                    clothes_type: 'cummerbund',
                    type_label: 'Cummerbund'
                },
                {
                    clothes_type: 'dinner_jacket',
                    type_label: 'Dinner Jacket'
                },
                {
                    clothes_type: 'dress',
                    type_label: 'Dress'
                },
                {
                    clothes_type: 'dressing_gown',
                    type_label: 'Dressing Gown'
                },
                {
                    clothes_type: 'dungarees',
                    type_label: 'Dungareesn'
                },
                {
                    clothes_type: 'fleece',
                    type_label: 'Fleece'
                },
                {
                    clothes_type: 'gloves',
                    type_label: 'Gloves'
                },
                {
                    clothes_type: 'hair_accessory',
                    type_label: 'Hair Accessory'
                },
                {
                    clothes_type: 'hat',
                    type_label: 'Hat'
                },
                {
                    clothes_type: 'hoody',
                    type_label: 'Hoody'
                },
                {
                    clothes_type: 'jacket',
                    type_label: 'Jacket'
                },
                {
                    clothes_type: 'jeans',
                    type_label: 'Jeans'
                },
                {
                    clothes_type: 'jogging_suit',
                    type_label: 'Jogging Suit'
                },
                {
                    clothes_type: 'jumper',
                    type_label: 'Jumper'
                },
                {
                    clothes_type: 'kaftan',
                    type_label: 'Kaftan'
                },
                {
                    clothes_type: 'kilt',
                    type_label: 'Kilt'
                },
                {
                    clothes_type: 'knickers',
                    type_label: 'Knickers'
                },
                {
                    clothes_type: 'kurta',
                    type_label: 'Kurta'
                },
                {
                    clothes_type: 'lingerie',
                    type_label: 'Lingerie'
                },
                {
                    clothes_type: 'nightgown',
                    type_label: 'Nightgown'
                },
                {
                    clothes_type: 'nightwear',
                    type_label: 'Nightwear'
                },
                {
                    clothes_type: 'overalls',
                    type_label: 'Overalls'
                },
                {
                    clothes_type: 'pashmina',
                    type_label: 'Pashmina'
                },
                {
                    clothes_type: 'polo_shirt',
                    type_label: 'Polo Shirt'
                },
                {
                    clothes_type: 'poncho',
                    type_label: 'Poncho'
                },
                {
                    clothes_type: 'pyjamas',
                    type_label: 'Pyjamas'
                },
                {
                    clothes_type: 'robe',
                    type_label: 'Robe'
                },
                {
                    clothes_type: 'romper',
                    type_label: 'Romper'
                },
                {
                    clothes_type: 'sarong',
                    type_label: 'Sarong'
                },
                {
                    clothes_type: 'scarf',
                    type_label: 'Scarf'
                },
                {
                    clothes_type: 'shawl',
                    type_label: 'Shawl'
                },
                {
                    clothes_type: 'shellsuit',
                    type_label: 'Shellsuit'
                },
                {
                    clothes_type: 'shirt',
                    type_label: 'Shirt'
                },
                {
                    clothes_type: 'shorts',
                    type_label: 'Shorts'
                },
                {
                    clothes_type: 'skirt',
                    type_label: 'Skirt'
                },
                {
                    clothes_type: 'socks',
                    type_label: 'Socks'
                },
                {
                    clothes_type: 'stockings',
                    type_label: 'Stockings'
                },
                {
                    clothes_type: 'suit',
                    type_label: 'Suit'
                },
                {
                    clothes_type: 'sweatshirt',
                    type_label: 'Sweatshirt'
                },
                {
                    clothes_type: 'swimming_costume',
                    type_label: 'Swimming Costume'
                },
                {
                    clothes_type: 'swimming_shorts',
                    type_label: 'Swimming Shorts'
                },
                {
                    clothes_type: 'swimming_trunks',
                    type_label: 'Swimming Trunks'
                },
                {
                    clothes_type: 'swimwear',
                    type_label: 'Swimwear'
                },
                {
                    clothes_type: 't_shirt',
                    type_label: 'T_shirt'
                },
                {
                    clothes_type: 'tailcoat',
                    type_label: 'Tailcoat'
                },
                {
                    clothes_type: 'tankini',
                    type_label: 'Tankini'
                },
                {
                    clothes_type: 'thong',
                    type_label: 'Thong'
                },
                {
                    clothes_type: 'tie',
                    type_label: 'Tie'
                },
                {
                    clothes_type: 'tights',
                    type_label: 'Tights'
                },
                {
                    clothes_type: 'top',
                    type_label: 'Top'
                },
                {
                    clothes_type: 'tracksuit',
                    type_label: 'Tracksuit'
                },
                {
                    clothes_type: 'trousers',
                    type_label: 'Trousers'
                },
                {
                    clothes_type: 'underwear',
                    type_label: 'Underwear'
                },
                {
                    clothes_type: 'vest',
                    type_label: 'Vest'
                },
                {
                    clothes_type: 'vest_underwear',
                    type_label: 'Vest Underwear'
                },
                {
                    clothes_type: 'waistcoat',
                    type_label: 'Waistcoat'
                },
                {
                    clothes_type: 'waterproof',
                    type_label: 'Waterproof'
                },
                {
                    clothes_type: 'zip',
                    type_label: 'Zip'
                },
                
            ],
            fields: [
                {
                    name: 'clothes_type'
                },
                {
                    name: 'type_label'
                }
            ]
        }, cfg)]);
    }
});