/*
 * File: app/store/FaasMonths.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.FaasMonths', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'FaasMonths',
            data: [
                {
                    faas_month_season_started: 'January'
                },
                {
                    faas_month_season_started: 'February'
                },
                {
                    faas_month_season_started: 'March'
                },
                {
                    faas_month_season_started: 'April'
                },
                {
                    faas_month_season_started: 'May'
                },
                {
                    faas_month_season_started: 'June'
                },
                {
                    faas_month_season_started: 'July'
                },
                {
                    faas_month_season_started: 'August'
                },
                {
                    faas_month_season_started: 'September'
                },
                {
                    faas_month_season_started: 'October'
                },
                {
                    faas_month_season_started: 'November'
                },
                {
                    faas_month_season_started: 'December'
                }
            ],
            fields: [
                {
                    name: 'faas_month_season_started'
                }
            ]
        }, cfg)]);
    }
});