/*
 * File: app/store/FaaSStages.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.FaaSStages', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'FaaSStages',
            data: [
                {
                    faas_stage: 'Seeding'
                },
                {
                    faas_stage: 'On'
                },
                {
                    faas_stage: 'One'
                },
                {
                    faas_stage: 'Oner'
                },
                {
                    faas_stage: 'Onero'
                },
                {
                    faas_stage: 'Oneroo'
                },
                {
                    faas_stage: 'Oneroof'
                },
                {
                    faas_stage: 'Harvest'
                }
            ],
            fields: [
                {
                    name: 'faas_stage'
                }
            ]
        }, cfg)]);
    }
});