/*
 * File: app/store/FaasYears.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.FaasYears', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'FaasYears',
            data: [
                {
                    faas_year_season_started: '2016'
                },
                {
                    faas_year_season_started: '2017'
                },
                {
                    faas_year_season_started: '2018'
                },
                {
                    faas_year_season_started: '2019'
                },
                {
                    faas_year_season_started: '2020'
                },
                {
                    faas_year_season_started: '2021'
                },
                {
                    faas_year_season_started: '2022'
                },
                {
                    faas_year_season_started: '2023'
                },
                {
                    faas_year_season_started: '2024'
                },
                {
                    faas_year_season_started: '2025'
                },
                {
                    faas_year_season_started: '2026'
                },
                {
                    faas_year_season_started: '2027'
                }
            ],
            fields: [
                {
                    name: 'faas_year_season_started'
                }
            ]
        }, cfg)]);
    }
});