/*
 * File: app/store/ImageMeasurementUnits.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.ImageMeasurementUnits', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ImageMeasurementUnits',
            data: [
                {
                    image_measurement_unit: 'millimeters',
                    measurement_label: 'Millimeters'
                },
                {
                    image_measurement_unit: 'centimeters',
                    measurement_label: 'Centimeters'
                },
                {
                    image_measurement_unit: 'inches',
                    measurement_label: 'Inches'
                },
                {
                    image_measurement_unit: 'picas',
                    measurement_label: 'Picas'
                },
                {
                    image_measurement_unit: 'pixels',
                    measurement_label: 'Pixels'
                },
                {
                    image_measurement_unit: 'points',
                    measurement_label: 'Points'
                },
                
            ],
            fields: [
                {
                    name: 'image_measurement_unit'
                },
                {
                    name: 'measurement_label'
                }
            ]
        }, cfg)]);
    }
});