/*
 * File: app/store/ShoeTarget.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.ShoeTarget', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ShoeTarget',
            data: [
                {
                    shoe_target_demography: 'adults',
                    target_label: 'Adults'
                },
                {
                    shoe_target_demography: 'teens',
                    target_label: 'Teenagers'
                },
                {
                    shoe_target_demography: 'preteens',
                    target_label: 'From Age Six(6) to Twelve(12) Years Old'
                },
                {
                    shoe_target_demography: 'babies',
                    target_label: 'From Age Zero(0) to Five(5) Years Old'
                },
                
            ],
            fields: [
                {
                    name: 'shoe_target_demography'
                },
                {
                    name: 'target_label'
                }
            ]
        }, cfg)]);
    }
});