/*
 * File: app/store/ShoesForWomenType.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.ShoesForWomenType', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ShoesForWomenType',
            data: [
                {
                    shoe_female_type: 'oxfords',
                    type_label: 'Oxfords'
                },
                {
                    shoe_female_type: 'pumps',
                    type_label: 'Pumps'
                },
                {
                    shoe_female_type: 'stilettos',
                    type_label: 'Stilettos'
                },
                {
                    shoe_female_type: 'kitten_heels',
                    type_label: 'Kitten Heels'
                },
                {
                    shoe_female_type: 'ankle_booties',
                    type_label: 'Ankle Booties'
                },
                {
                    shoe_female_type: 'ankle_strap_heels',
                    type_label: 'Ankle Strap Heels'
                },
                {
                    shoe_female_type: 'wedges',
                    type_label: 'Wedges'
                },
                {
                    shoe_female_type: 'cone_heels',
                    type_label: 'Cone Heels'
                },
                {
                    shoe_female_type: 'athletic_shoes',
                    type_label: 'Athletic Shoes'
                },
                {
                    shoe_female_type: 'gladiator_sandals',
                    type_label: 'Gladiator Sandals'
                },
                {
                    shoe_female_type: 'gladiator_boots',
                    type_label: 'Gladiator Boots'
                },
                {
                    shoe_female_type: 'sling_back_heels',
                    type_label: 'Sling Back Heels'
                },
                {
                    shoe_female_type: 'ballerina_flats',
                    type_label: 'Ballerina Flats'
                },
                {
                    shoe_female_type: 'open_toe_sandals',
                    type_label: 'Open Toe Sandals'
                },
                {
                    shoe_female_type: 'peep_toe_heels',
                    type_label: 'Peep Toe Heels'
                },
                {
                    shoe_female_type: 'cork_high_heels',
                    type_label: 'Cork High Heels'
                },
                {
                    shoe_female_type: 'platform',
                    type_label: 'Platform'
                },
                {
                    shoe_female_type: 'spool_heels',
                    type_label: 'Spool Heels'
                },
                {
                    shoe_female_type: 'mary_janes',
                    type_label: 'Mary Janes'
                },
                {
                    shoe_female_type: 'scarpin',
                    type_label: 'Scarpin'
                },
                {
                    shoe_female_type: 'espadrille_heels',
                    type_label: 'Espadrille Heels'
                },
                {
                    shoe_female_type: 'mules',
                    type_label: 'Mules'
                },
                {
                    shoe_female_type: 'thigh_high_boots',
                    type_label: 'Thigh High Boots'
                },
                {
                    shoe_female_type: 'loafer',
                    type_label: 'Loafer'
                },
                {
                    shoe_female_type: 'canvas',
                    type_label: 'Canvas'
                },
                {
                    shoe_female_type: 'fantasy',
                    type_label: 'Fantasy'
                },
                {
                    shoe_female_type: 'slippers',
                    type_label: 'Slippers'
                },
                {
                    shoe_female_type: 'trainers',
                    type_label: 'Trainers'
                },
                {
                    shoe_female_type: 'snickers',
                    type_label: 'Snickers'
                },
                
            ],
            fields: [
                {
                    name: 'shoe_female_type'
                },
                {
                    name: 'type_label'
                }
            ]
        }, cfg)]);
    }
});