/*
 * File: app/store/VideoScanType.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.VideoScanType', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'VideoScanType',
            data: [
                {
                    footage_scan_type: 'progressive',
                    type_label: 'Progressive - This is the industry standard'
                },
                {
                    footage_scan_type: 'interlaced',
                    type_label: 'Interlaced - This should be avoided except you know what you are doing'
                }
            ],
            fields: [
                {
                    name: 'footage_scan_type'
                },
                {
                    name: 'type_label'
                }
            ]
        }, cfg)]);
    }
});