/*
 * File: app/store/VideoFormats.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.store.VideoFormats', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'VideoFormats',
            data: [
                {
                    footage_format: 'mp4',
                    format_label: 'MP4'
                },
                {
                    footage_format: 'avi',
                    format_label: 'AVI'
                },
                {
                    footage_format: 'wmv',
                    format_label: 'WMV'
                },
                {
                    footage_format: 'flv',
                    format_label: 'FLV'
                },
                {
                    footage_format: 'mov',
                    format_label: 'MOV'
                }
            ],
            fields: [
                {
                    name: 'footage_format'
                },
                {
                    name: 'format_label'
                }
            ]
        }, cfg)]);
    }
});